vanetnuggets/vanetlab-fe

src/lib/DragContainer.svelte
src/lib/DragDrop/ListNodes.svelte
src/lib/scenario/Container.svelte
src/lib/scenario/Scenario.svelte
src/lib/scenario/ServerApp.svelte
src/lib/scenario/Simulation.svelte
src/lib/scenario/Topology.svelte
src/store/store.js

Upratanie užívateľských vstupov, rozdelenie nodov, atď

Scenario settings

---

src/lib/scenario/ClientApp.svelte
src/lib/scenario/Container.svelte
src/lib/scenario/Topology.svelte
src/store/store.js

New attribute to container component.
Added feature to be able to open only one container.
pls apruv

Scenario settings - new attribute

---

src/lib/scenario/Container.svelte

I.. don't know. Branches go brrrr
Just a small refactor of ugly and unreadable ternary operator used for opening containers

Scenario settings - small refactor

---

src/App.svelte
src/lib/DragDrop/ListNodes.svelte
src/lib/DragDrop/Node.svelte
src/lib/sipky/sipky.js

som to trochu zrefaktoroval lebo som to nevedel citat a tak a aj deletovanie sipocok by malo ficat

fix delete sipocky

---

package-lock.json
package.json
src/App.svelte
src/app.css
src/assets/default.css
src/lib/DragDrop/DragContainer.svelte
src/lib/DragDrop/ListNodes.svelte
src/lib/DragDrop/Node.svelte
src/lib/DragDrop/NotFound.svelte
src/lib/layouts/AppLayout.svelte
src/lib/layouts/BottomBar.svelte
src/lib/layouts/LeftDrawer.svelte
src/lib/layouts/RightDrawer.svelte
src/lib/layouts/TopBar.svelte
src/lib/scenario/ClientApp.svelte
src/lib/scenario/Container.svelte
src/lib/scenario/Scenario.svelte
src/lib/scenario/ServerApp.svelte
src/lib/scenario/Simulation.svelte
src/lib/scenario/Topology.svelte
src/lib/sipky/sipky.js
src/lib/vizualize/Summary.svelte
src/main.js
src/services/Api.js
src/store/store.js

tak a je to tu.
nastal ten den ? 
funkcny prototyp ? 
este to chce trosku doladit detaily, ako napriklat stahovanie .pcap suboru zo sumaru a css layoutu nech tam nejsu scrollbary vsade jaj ale inak celkom pohoda ne

Romanove api

---

src/lib/scenario/Container.svelte
src/lib/sipky/sipky.js

sipky container fix + change type to dropdown

---

Dockerfile
src/lib/scenario/containers/Basic.svelte

Point-to-point is point to point

only 2 nodes can be in p2p network

---

docker-compose-prod.yml
package-lock.json
package.json
src/App.svelte
src/lib/DragDrop/ListNodes.svelte
src/lib/DragDrop/Node.svelte
src/lib/layouts/BottomBar.svelte
src/lib/scenario/Scenario.svelte
src/lib/scenario/Topology.svelte
src/lib/sipky/sipky.js
src/lib/vizualize/ConsoleLogs.svelte
src/lib/vizualize/SourceCode.svelte
src/lib/vizualize/Summary.svelte
src/lib/vizualize/TraceLogs.svelte
src/services/Api.js
src/services/PresetService.js
src/store/store.js
traefik.yml

vselico som dodal musime merdzovat postupne

Mult scenarios

---

src/lib/scenario/Container.svelte
src/lib/scenario/Topology.svelte
src/lib/scenario/containers/Basic.svelte
src/lib/sipky/sipky.js
src/store/store.js

Container remove

---

src/lib/network/Network.svelte

Niekto mi povedal, že mám zmeniť názvy, tak som ich zmenil. Raz. Keby mi to bol povedal aj druhýkrát, zmením ich aj v druhom súbore. 🤷

:bug: complete change of attributes names

---

src/lib/Canvas/Canvas.svelte
src/lib/network/Network.svelte
src/lib/network/Networks.svelte
src/lib/network/Switch.svelte
src/lib/topology/L2.svelte
src/lib/topology/L3.svelte
src/lib/topology/Mobility.svelte
src/lib/topology/NodeInfo.svelte
src/store/store.js

Takze upravil som lavy drawer tak, aby sa pozicia priradzovala k casu. Takto mozme v dalsom update pridat prekreslovanie nodov podla aktualneho casu. Upravil som L2 aby sa automaticky priradovala podla typu siete a snazil sa osetrit vsetky mozne scenare. L3 este dorobim zajtra ale to bude rychlovka

Right drawer - nove L2 a pozicia podla casu

---

package-lock.json
package.json
src/lib/Canvas/Canvas.svelte
src/lib/Canvas/TimeManagment.svelte
src/store/scenario.js

Pridal som slider na cas a aby si pouzivatel mohol zvolit maximalny cas. Ten maximalny cas sa vie aj sam nastavit

add time managment (time slider and max time)

---

src/lib/Canvas/Canvas.svelte
src/lib/Canvas/TimeManagment.svelte
src/lib/topology/L2.svelte
src/lib/topology/Mobility.svelte

No fixol som to podla toho casu. Pri vykreslovani, ak neexistuje priamo mobility aktualneho casu, tak node zostava na pozicii najblizsieho mensieho casu. Kluce mobility su uz vo formate current_time.".0". Riesim aj situaciu ak je nahodou dictionary v inom tvare, aby nam to nehadzalo blbosti ale to vykreslilo

moving nodes according to current time

---

src/lib/topology/L2.svelte
src/lib/topology/L2attributes.svelte
src/lib/topology/L3.svelte

Pridal som optional atributy a plne konfigoravateelne l3

Right drawer

---

src/lib/Canvas/Canvas.svelte
src/lib/topology/L2.svelte
src/lib/topology/L2attributes.svelte
src/lib/topology/L3.svelte
src/lib/topology/Mobility.svelte
src/lib/topology/NodeInfo.svelte

Pridal som moznost mazat nody a trosku som poosetroval edge cases pri mobility

add removing of nodes and mobility bugs

---

src/lib/Canvas/Canvas.svelte

indexovanie v nodearr je iné než $nodes 😠

:man_firefighter: :fire: hotfix remove bugu

---

src/services/LoadService.js

len taka malicka drobnost aby to nespadlo ked to runnes.

add connections and routing to final config

---

index.html
src/lib/Canvas/Canvas.svelte
src/lib/topology/SdnNeighbors.svelte
src/store/store.js

nazor
@omartinka @andrejdubak @fud4ly

qol sdn neighbors

---

src/lib/Canvas/Canvas.svelte

fixed ovs switch deletion when adding nodes to it

---

src/assets/edit.svg
src/lib/Canvas/Canvas.svelte
src/lib/topology/L2.svelte
src/lib/topology/L2attributes.svelte
src/lib/topology/L3.svelte
src/lib/topology/L3attributes.svelte
src/lib/topology/Mobility.svelte
src/lib/topology/NodeInfo.svelte

Pridal som wifi standardy a pridal moznost editovacieho praveho drawera, aby pouzivatel nemohol len tak hocico menit bez validacie

Validation

---

src/lib/api/scenarios.js
src/lib/layouts/TopBar.svelte
src/lib/layouts/welcome/LoadRemote.svelte
src/lib/vizualize/Summary.svelte
src/services/Api.js
src/services/NodeService.js
src/services/Ws.js
src/services/initService.js
src/store/summary.js

concurrency

---

src/App.svelte
src/lib/Pages/About.svelte
src/lib/layouts/Welcome.svelte

trenujem si pisanie dokumentacii

about page

---

src/lib/Canvas/Canvas.svelte
src/services/LoadService.js
src/store/store.js

co to tu je za bordel approvnit emi rekvest

nalozene ukladajuce sa labely

---

src/services/LoadService.js

removed console log

---

src/assets/default.css
src/lib/Canvas/Canvas.svelte
src/lib/Canvas/CanvasBar.svelte
src/lib/Pages/About.svelte
src/lib/layouts/TopBar.svelte
src/lib/layouts/welcome/LoadRemote.svelte
src/lib/network/Network.svelte
src/lib/topology/L2.svelte
src/lib/topology/L2attributes.svelte
src/lib/topology/L3.svelte
src/lib/topology/L3attributes.svelte
src/lib/vizualize/Summary.svelte
src/services/Validations/ValidationCheck.js
src/services/Validations/Validators.js
src/store/validation.js

Zrusil som nutnost vyplnania l3. Teraz pouzivatel nemusi l3 vyplnat. Ale ak ju uz vyplni tak je validovana. Svoju brangu som najprv mergol s mainom, tak snad to znova nepadne

set l3 and l2 fields as not requared

---

src/lib/layouts/welcome/FromSumo.svelte
src/lib/layouts/welcome/NewSim.svelte

nwm preco ale nedali sa spravit 2 scenare po sebe, vyzera ze v init valules je nejaky borderl ale nwm odkial

fixed ability to make 2 scenarios in a row, idk whi
